### ISSUE TITLE
jax tree_multimap deprecated

### ISSUE THREAD

**Issue by jackgoffinet** [lindermanlab/ssm-jax#37]
Hi, I'm excited to start using this codebase.

I followed the "installation for development" instructions in the README, but then ``from ssm.hmm import GaussianHMM``  gives me an error about ``tree_multimap``. It looks like `jax.tree_util.tree_multimap` was removed in jax v0.3.16 ([changelog](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-16)) and the latest release is 0.3.20. It look like tree_multimap was simply replaced by `jax.tree_utils.tree_map` and that the functionality is the same ([jax issue](https://github.com/google/jax/issues/5746), [PR](https://github.com/google/jax/pull/10126)).

In this repo, tree_multimap is only used in `ssm.utils.tree_all_equal`, so it should be straightforward to remove.

Best,

Jack

**Comment by slinderman** [comment]
Hi Jack, 

Thanks for the interest and heads up. We joined forces with ProbML and are developing a new library at https://github.com/probml/ssm-jax/ We'll make a public release of that library (probably with a new name, tbd) in the coming weeks, at which point I'll officially deprecate this repo.  

Best,
Scott

**Comment by jackgoffinet** [comment]
Great, thanks for letting me know! I'll check that out.

**Comment by slinderman** [comment]
FYI, I did just push a fix to this in case you're still using this repo.
